// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9QbF5KEbTFoJ8xQDIUOE8AknGpl03R0',
    appId: '1:994427204003:web:e9bea2f1b8c5860cd02a16',
    messagingSenderId: '994427204003',
    projectId: 'flutter-chat-app-f3243',
    authDomain: 'flutter-chat-app-f3243.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f3243.appspot.com',
    measurementId: 'G-51HES87L9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS0Or7OMZMCze0xrzxBGljxQE4NE94cGE',
    appId: '1:994427204003:android:4336fd2bd53f8ac4d02a16',
    messagingSenderId: '994427204003',
    projectId: 'flutter-chat-app-f3243',
    storageBucket: 'flutter-chat-app-f3243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRyps49anvGQeiE6Cg22kuUlKZrQ752zM',
    appId: '1:994427204003:ios:851142892e22f1bcd02a16',
    messagingSenderId: '994427204003',
    projectId: 'flutter-chat-app-f3243',
    storageBucket: 'flutter-chat-app-f3243.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRyps49anvGQeiE6Cg22kuUlKZrQ752zM',
    appId: '1:994427204003:ios:851142892e22f1bcd02a16',
    messagingSenderId: '994427204003',
    projectId: 'flutter-chat-app-f3243',
    storageBucket: 'flutter-chat-app-f3243.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
